---
title: "testing"
author: "Rizny Mubarak"
date: "2023-10-08"
output: html_document
---

### Load Data

```{r}
library(forecast)
library(tsutils)
library(MLmetrics)
library(glmnet)
source('functions.r')
```

```{r setup, include=FALSE}
load('dataTour.Rdata')
```

## France

```{r}
y <- dataTour$UK
```

```{r}
plot(y, main = "France")
```

### 1. in- and out-of-sample and data exploration

```{r}
datasets <- create_datasets(y, 'France', c(2000, 1), c(2018, 4), 0.8)
```

```{r}
explore_data(datasets$train)
```

### 2. Exponential smoothing

#### 2.1 Information criteria

```{r}
fit <- ets(datasets$train)
fit
```

```{r}
selected_model <- data.frame()
```

```{r}
selected_model <- append_unique_model(auto_model(datasets$train),selected_model)
```

```{r}
selected_model  <- append_unique_model(aicc_model(datasets$train),selected_model)
 
```

```{r}
selected_model
```

```{r}
selected_model[[1]]
```

#### 2.2 Validation Error

```{r}
selected_model <- append_unique_model(mape_model(datasets$train, 0.8, selected_model[[1]]),selected_model)
```

```{r}
selected_model
```

#### 2.3 Rolling origin In Sample

```{r}
selected_model_ROCV <- ROCV_Model(datasets$train, 0.8, selected_model, 8)

```

```{r}
selected_model  <- append_unique_model(selected_model_ROCV,selected_model)
```

```{r}
selected_model
```

#### 2.4 Out-of-sample evaluation

```{r}
ROCV_Model_Out(datasets$train, 0.8, selected_model, 8)
```

#### 2.5 Forecast combination with AIC weights

```{r}
frcComb <- find_weighted_combination(datasets$train,selected_model, length(datasets$test))
```

```{r}
calculate_MAPE(frcComb,datasets$test)
```

### 2. Regression

```{r}
data_reg <- create_datasets(y, 'France', c(2000, 1), c(2018, 4), 0.95)
```

```{r}
n <- length(data_reg$train)
n
```

```{r}
pacf <- pacf(data_reg$train)

```

```{r}
X <- array(NA,c(n,5))
```

```{r}
for (i in 1:5){
X[i:n,i] <- france.trn[1:(n-i+1)]
}
#Name the columns
colnames(X) <- c("y",paste0("lag",1:4))
X[1:10,]
```

```{r}
X[(n-9):n,]
```

```{r}
X <- as.data.frame(X)
plot(X)
```

#### 2.1 Lags - Models

```{r}
# The complete model
fit1 <- lm(y~.,data=X)
summary(fit1)
```

```{r}
# The stepwise model
fit2 <- step(fit1,trace = 0)
summary(fit2)
```

```{r}
c(AIC(fit1),AIC(fit2))
```

```{r}
# In-sample fit:
plot(X$y,type="l")
frc <- predict(fit2,X)
lines(frc,col="red")
```

```{r}
formula(fit2)
```

```{r}
frc1 <- array(NA,c(8,1))
for (i in 1:8){
Xnew <- tail(france.trn,4)
Xnew <- c(Xnew,frc1)
Xnew <- Xnew[i:(3+i)]
Xnew <- Xnew[4:1]
Xnew <- array(Xnew, c(1,4))
colnames(Xnew) <- paste0("lag",1:4)
Xnew <- as.data.frame(Xnew)
# Forecast
frc1[i] <- predict(fit2,Xnew)
}
```

```{r}
frc1 <- ts(frc1,frequency=frequency(france.tst),start=start(france.tst))
```

```{r}
ts.plot(france.trn,france.tst,frc1,col=c("black","black","red"))
```

-   Handle seasonality

```{r}
D <- rep(1:4,7) # Replicate 1:4 16 times
D <- factor(D)
D
```

```{r}
class(D)
```

```{r}
factor(rep(c("Q1","Q2","Q3","Q4"),7))
```

```{r}
X2 <- cbind(X,D)
colnames(X2) <- c(colnames(X2)[1:5],"D")
X2
```

```{r}
fit3 <- lm(y~.,data=X2)
summary(fit3)
```

```{r}
# Find NA in X2
idx <- is.na(X2)
idx <- rowSums(idx)
idx <- idx == 0
```

```{r}
fit_temp <- lm(y~.,data=X2[idx,])
# fit_temp is the same as fit3, without the first NA part
fit4 <- step(fit_temp,trace = 0, direction = "both")
summary(fit4)
```

```{r}
AIC(fit3)
```

```{r}
c(AIC(fit2),AIC(fit4))
```

```{r}
frc <- predict(fit4,X2)
ts.plot(france.trn,frc,col=c("black","red"))
```

```{r}
frc2 <- array(NA, c(8, 1))
for (i in 1:8) {
  Xnew <- tail(france.trn, 4)
  Xnew <- c(Xnew, frc2)
  Xnew <- Xnew[i:(3 + i)]
  Xnew <- Xnew[4:1]
  Xnew <- array(Xnew, c(1, 4))
  colnames(Xnew) <- paste0("lag", 1:4)
  Xnew <- as.data.frame(Xnew)
  D <- as.factor(rep(1:4, 2)[i])
  Xnew <- cbind(Xnew, D)
  # Forecast
  frc2[i] <- predict(fit4, Xnew)
}
frc2
```

```{r}
cbind(frc1, frc2)
```

```{r}
# Transform to time series
frc2 <- ts(frc2,frequency=frequency(france.tst),start=start(france.tst))
# Plot
ts.plot(france.trn,france.tst,frc1,frc2,col=c("black","black","red","blue"))
legend("bottomright",c("Autoregressive","Dummies"),col=c("red","blue"),lty=1)
```

-   Handle trends

```{r}
X3 <- X
```

```{r}
# The function ncol() counts how many columns
for (i in 1:ncol(X3)){
X3[,i] <- c(NA,diff(X3[,i]))
}
print(X3)
```

```{r}
summary(lm(y~.,X3))
```

```{r}
X3 <- na.omit(X3)
fit5 <- step(lm(y ~ ., data = X3), trace = 0)
summary(fit5)
```

```{r}
summary(fit5)
```

```{r}
frc3 <- array(NA,c(8,1))
for (i in 1:8){
# Calculate the differences of the in-sample data
france.diff <- diff(france.trn)
# Create lags - same as before
Xnew <- tail(france.diff,4)

Xnew <- c(Xnew,frc3)
Xnew <- Xnew[i:(3+i)]
Xnew <- Xnew[4:1]
Xnew <- array(Xnew, c(1,4))
colnames(Xnew) <- paste0("lag",1:4)
Xnew <- as.data.frame(Xnew)
# Forecast
frc3[i] <- predict(fit5,Xnew)
}
```

```{r}
# Transform to time series
frc3 <- ts(frc3,frequency=frequency(france.tst),start=start(france.tst))
# Plot
ts.plot(diff(france.trn),frc3,col=c("black","red"))
```

```{r}
frc3ud <- cumsum(c(tail(france.trn,1),frc3))
frc3ud <- frc3ud[-1]
```

```{r}
frc3ud <- ts(frc3ud,frequency=frequency(france.tst),start=start(france.tst))
ts.plot(france.trn,france.tst,frc1,frc2,frc3ud,col=c("black","black","red","blue","gold"))
legend("bottomright",c("Autoregressive","Dummies","Difference"),col=c("red","blue","gold"),lty=1)
```

```{r}
actual <- matrix(rep(france.tst,3),ncol=3)
actual
```

```{r}
error <- abs(actual - cbind(frc1,frc2,frc3ud))/actual * 100
MAPE <- colMeans(error)
MAPE
```

#### 2.2 Lasso

```{r}
xx <- as.matrix(X[-(1:4),-1])
yy <- as.matrix(X[-(1:4),1])
```

```{r}
lasso <- cv.glmnet(x=xx,y=yy, grouped = FALSE)
```

```{r}
coef(lasso)
```

```{r}
plot(lasso)
```

```{r}
frc2 <- array(NA,c(8,1))
for (i in 1:8){
# Create inputs - note for lasso we do not transform these into data.frame
Xnew <- c(tail(france.trn,4),frc2)
Xnew <- (Xnew[i:(3+i)])[4:1]
Xnew <- array(Xnew, c(1,4))
colnames(Xnew) <- paste0("lag",1:4)
# Forecast
frc2[i] <- predict(lasso,Xnew)
}
```

```{r}
# Transform to time series
frc2 <- ts(frc2,frequency=frequency(france.tst),start=start(france.tst))
# Plot together with fit2
ts.plot(france.trn,france.tst,frc1,frc2,col=c("black","black","red","blue"))
legend("bottomright",c("OLS","Lasso"),col=c("red","blue"),lty=1)
```

```{r}
ridge <- cv.glmnet(x=xx,y=yy,alpha=0, grouped = FALSE)
coef(ridge)
```

```{r}
cc <- as.matrix(cbind(coef(lasso),coef(ridge)))
colnames(cc) <- c("lasso","ridge")
round(cc,3)
```

```{r}
frc3 <- array(NA,c(8,1))
for (i in 1:8){
# Create inputs - note for lasso we do not transform these into data.frame
Xnew <- c(tail(france.trn,4),frc2)
Xnew <- (Xnew[i:(3+i)])[4:1]
Xnew <- array(Xnew, c(1,4))
colnames(Xnew) <- paste0("lag",1:4)
# Forecast
frc3[i] <- predict(ridge,Xnew)
}
```

```{r}
frc3 <- ts(frc3,frequency=frequency(france.tst),start=start(france.tst))
# Plot together with fit2
ts.plot(france.trn,france.tst,frc1,frc2,frc3,col=c("black","black","red","blue","green"))
legend("bottomright",c("OLS","Lasso","Ridge"),col=c("red","blue","green"),lty=1)
```
