---
title: "Project In Forcasting"
author: "Rizny Mubarak"
date: "2023-10-05"
output: pdf_document
---

```{r}
# Load Library
library(ggplot2)
library(forecast)
library(tsutils)
library(MLmetrics)
```

### 1. Load Data

```{r}
load('dataTour.Rdata')

```

```{r}
y <- dataTour$UK
```

```{r}
y <- window(y,end=c(2018,quarter = 4))

```

```{r}
NROW(y)
```

```{r}
plot(y, main = "Origin Countries")
```

```{r}
y.tst <- tail(y,16)
y.trn <- head(y,60)
```

```{r}
cma_list <- lapply(colnames(y.trn), 
                   function(cols){  
                     cmav(y.trn[, cols], outplot = 1) 
                     title(main = cols)
                     })
```

### 2. Forecasting

#### 2.1 Selection of forecasts using information criteria

```{r}
best_models <- list()
```

```{r}
fit <- lapply(y.trn, function(col) ets(col))
```

```{r}
# Level models
fit1 <- lapply(y.trn, function(col) ets(col,model="ANN"))
# Seasonal models
fit2 <- lapply(y.trn, function(col) ets(col,model="ANA"))
# Linear trend models
fit3 <- lapply(y.trn, function(col) ets(col,model="AAN",damped=FALSE))
# Damped trend models
fit4 <- lapply(y.trn, function(col) ets(col,model="AAN",damped=TRUE))
# Trend seasonal models
fit5 <- lapply(y.trn, function(col) ets(col,model="AAA",damped=FALSE))
# Damped trend seasonal models
fit6 <- lapply(y.trn, function(col) ets(col,model="AAA",damped=TRUE))
```

```{r}
# List of models
models <- list(fit1, fit2, fit3, fit4, fit5, fit6)

# List of model names
model_names <- c("ANN", "ANA", "AAN", "AAdN", "AAA", "AAdA")

# Initialize a data frame to store the results
aiccs <- data.frame(
  Country = character(0),
  ANN = numeric(0),
  ANA = numeric(0),
  AAN = numeric(0),
  AAdN = numeric(0),
  AAA = numeric(0),
  AAdA = numeric(0),
  stringsAsFactors = FALSE
)

# Iterate through the countries
for (country_name in colnames(y.trn)) {
  # Initialize a vector to store AICc values for this country
  aicc_values <- character(0)
  
  # Iterate through the models
  for (i in 1:length(models)) {
    model <- models[[i]]
    country_fit <- model[[country_name]]
    aicc_value <- round(country_fit$aicc, 3)
    aicc_values <- c(aicc_values, aicc_value)
  }
  aic_min = model_names[(which.min(aicc_values))]
  auto = paste(fit[[country_name]]$components[1], fit[[country_name]]$components[2], fit[[country_name]]$components[3], sep = "")
  
  best_models <- rbind(best_models, c(Auto=auto,Aicc_min = aic_min))
  
  aiccs <- rbind(aiccs, c(country_name, aicc_values))
}

# Update column names
colnames(aiccs) <- c("Country", model_names)
```

```{r}
aiccs

```

```{r}
rownames(best_models) <- colnames(y.trn)
best_models
```

#### 2.2 Selection of forecasts using a validation set

```{r}
y.ins <- head(y.trn,44)
y.val <- tail(y.trn,16)
```

```{r}
h <- 4
```

```{r}
types <- as.list(setNames(best_models[,1], rownames(best_models)))
```

```{r}
#Automatic Models
fitv <- lapply(names(types), function(country) {
  ets(y.trn[,country], model = types[[country]])
})
names(fitv) <- names(types)
```

```{r}

fit1v <- lapply(y.ins, function(col) ets(col,model="ANN"))
# Seasonal models
fit2v <- lapply(y.ins, function(col) ets(col,model="ANN"))
# Linear trend models
fit3v <- lapply(y.ins, function(col) ets(col,model="ANN",damped=FALSE))
# Damped trend models
fit4v <- lapply(y.ins, function(col) ets(col,model="AAN",damped=TRUE))
# Trend seasonal models
fit5v <- lapply(y.ins, function(col) ets(col,model="AAA",damped=FALSE))
# Damped trend seasonal models
fit6v <- lapply(y.ins, function(col) ets(col,model="AAA",damped=TRUE))
```

```{r}
frcav <- lapply(fitv,function(frc) forecast(frc,h=h))
frc1v <- lapply(fit1v,function(frc) forecast(frc,h=h))
frc2v <- lapply(fit2v,function(frc) forecast(frc,h=h))
frc3v <- lapply(fit3v,function(frc) forecast(frc,h=h))
frc4v <- lapply(fit4v,function(frc) forecast(frc,h=h))
frc5v <- lapply(fit5v,function(frc) forecast(frc,h=h))
frc6v <- lapply(fit6v,function(frc) forecast(frc,h=h))
frc7v <- sapply(names(types), function(frc) {
  unlist(tail(y.val[,frc],8)[1:h])
}, simplify = FALSE)
```

```{r}

errav <- lapply(names(types), function(country) {
  m <- frcav[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})

err1v <- lapply(names(types), function(country) {
  m <- frc1v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})

err2v <- lapply(names(types), function(country) {
  m <- frc2v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})

err3v <- lapply(names(types), function(country) {
  m <- frc3v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})

err4v <- lapply(names(types), function(country) {
  m <- frc4v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})

err5v <- lapply(names(types), function(country) {
  m <- frc5v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})
err6v <- lapply(names(types), function(country) {
  m <- frc6v[[country]]
  round(MAPE(m$mean,y.val[, country][1:h]),digits = 3)
})
err7v <- lapply(names(types), function(country) {
  m <- frc7v[[country]]
  round(MAPE(m,y.val[, country][1:h]),digits = 3)
})
```

```{r}
errv <- cbind(errav,err1v, err2v, err3v, err4v, err5v, err6v, err7v)
```

```{r}
colnames(errv) <- c("Auto","ANN","ANA","AAN","AAdN","AAA","AAdA","Naive")
```

```{r}
errv
```

```{r}
best_models <- cbind(best_models,"MAPE" = colnames(errv)[apply(errv, 1, which.min)])

best_models
```

```{r}
omax <- length(y.val[,'France']) - h + 1
omax
```

```{r}
models <- c("ANA","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive")
models <- rbind(France=models,USA=c("MNM","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))
models <- rbind(models,Germany=c("MNA","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))
models <- rbind(models,Ireland=c("ANA","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))
models <- rbind(models,Spain=c("MAM","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))
models <- rbind(models,Rest=c("ANA","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))
models <- rbind(models,Total=c("ANA","ANN", "ANA", "AAN", "AAN", "AAA", "AAA", "Naive"))

damped <- c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE)
damped <- rbind(France=damped,USA=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))
damped <- rbind(France=damped,Germany=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))
damped <- rbind(France=damped,Ireland=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))
damped <- rbind(France=damped,Spain=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))
damped <- rbind(France=damped,Rest=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))
damped <- rbind(France=damped,Total=c(FALSE,FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE))

```

```{r}
models
damped
```

```{r}
errMean <- list()
err <- array(NA,c(omax,8))
frcs <- array(NA,c(h,8))
```

```{r}
# For each forecast origin
countries = rownames(best_models) 
for (n in 1:7) {
  for (o in 1:omax) {
    y.ins <- head(y.trn, 44 - 1 + o)
    y.val <- tail(y.trn, 16 - o + 1)
    # Fit and forecast
    
    for (m in 1:7) {
      fitTemp <-
        ets(y.ins[,countries[n]], model = models[n, m], damped = damped[n, m])
      frcs[, m] <- forecast(fitTemp, h = h)$mean
      # err[o,m] <- mean(abs(y.val[1:h] - frcs[,m]))
      err[o, m] <- round(MAPE(frcs[, m],y.val[, countries[n]][1:h]),digits = 3)
    }
    #Forecast using the seasonal naive
    frcs[, 8] <- tail(y.ins[, countries[n]], 4)[1:h]
    # err[o,8] <- mean(abs(y.val[1:h] - frcs[,8]))
    err[o, 8] <- round(MAPE(frcs[, 8],y.val[, countries[n]][1:h]),digits = 3)
    
  }
  errMean <- rbind(errMean,colMeans(err))
}

```

```{r}
colnames(errMean) <- c("Auto","ANN","ANA","AAN","AAdN","AAA","AAdA", "Naive")
rownames(errMean) <- names(types)
errMean
```

```{r}
# Add ROCV models to Best_list
best_models <-  cbind(best_models, "ROCV"= colnames(errMean)[apply(errMean, 1, which.min)])

```

```{r}
best_models
```

#### 3. Out-of-sample evaluation

```{r}
# modelsTest <- c("ANA", "MNM", "AAA","AAA", "Naive", "CombMean", "CombMedian")
# dampedTest <- c(FALSE, FALSE, TRUE,FALSE)
```
